In [1]:
import torch
from bitnetb158.nn import BitLinearb158

input_data = torch.randn(5, 4)
model = BitLinearb158(4, 4)

In [2]:
model.weight

Parameter containing:
tensor([[ 0.0362, -0.3931, -0.4709,  0.4073],
        [ 0.1506, -0.3157, -0.2222,  0.0243],
        [-0.1678, -0.2416, -0.4693,  0.0646],
        [-0.0044, -0.2474, -0.3790, -0.0697]], requires_grad=True)

In [3]:
original_output = model(input_data)
original_output

tensor([[-0.6686, -0.6319, -0.2369, -0.4351],
        [ 0.4450, -0.1270,  0.3352,  0.1034],
        [-0.0506,  0.2493, -0.1207,  0.0636],
        [ 0.7204,  0.3227,  0.3689,  0.3451],
        [ 0.4206,  0.4910,  0.1149,  0.3023]], grad_fn=<MulBackward0>)

In [4]:
model.convert_weights_to_packed()
model.weight

tensor([[104],
        [ 41],
        [ 42],
        [ 40]], dtype=torch.int8)

In [5]:
model.unpack_ternary(model.weight)

tensor([[ 0, -1, -1,  1],
        [ 1, -1, -1,  0],
        [-1, -1, -1,  0],
        [ 0, -1, -1,  0]])

In [6]:
display(original_output)
display(model.forward_after_packed(input_data))

tensor([[-0.6686, -0.6319, -0.2369, -0.4351],
        [ 0.4450, -0.1270,  0.3352,  0.1034],
        [-0.0506,  0.2493, -0.1207,  0.0636],
        [ 0.7204,  0.3227,  0.3689,  0.3451],
        [ 0.4206,  0.4910,  0.1149,  0.3023]], grad_fn=<MulBackward0>)

tensor([[-0.6686, -0.6319, -0.2369, -0.4351],
        [ 0.4450, -0.1270,  0.3352,  0.1034],
        [-0.0506,  0.2493, -0.1207,  0.0636],
        [ 0.7204,  0.3227,  0.3689,  0.3451],
        [ 0.4206,  0.4910,  0.1149,  0.3023]], grad_fn=<MulBackward0>)

In [7]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([ 0.4629,  0.4755, -0.4406, -0.2057], requires_grad=True)
Parameter containing:
tensor(0.2290, requires_grad=True)
